<Project Sdk="Microsoft.NET.Sdk.Razor">
	<!-- ============================================================================ -->
	<!-- CORE PROPERTIES -->
	<!-- ============================================================================ -->

<PropertyGroup>
	<!-- Target Framework Defined on Build.Props Do to Add Another here-->

	<OutputType>Library</OutputType>
	<TreatWarningsAsErrors>false</TreatWarningsAsErrors>
	<Namespace>ExxerAI.UI.Library</Namespace>
	<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	<!-- Language Features -->
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

	<!-- Razor Class Library Configuration -->
	<RazorLangVersion>Latest</RazorLangVersion>
	<AddRazorSupportForMvc>true</AddRazorSupportForMvc>

	<!-- Library Configuration -->
	<IsPackable>true</IsPackable>
	<GenerateDocumentationFile>true</GenerateDocumentationFile>

	<!-- Application Information -->
	<AssemblyTitle>ExxerAI UI Component Library</AssemblyTitle>
	<Description>Shared UI Components for ExxerAI Applications</Description>
	<Company>Exxerpro Solutions</Company>
	<Product>ExxerAI Intelligence System</Product>
	<Title>ExxerAI.UI.Library</Title>

  </PropertyGroup>

	<!-- ============================================================================ -->
	<!-- PACKAGE REFERENCES - ENTITY FRAMEWORK -->
	<!-- ============================================================================ -->
  <ItemGroup Label="Entity Framework">

	  <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

	<!-- ============================================================================ -->
	<!-- PACKAGE REFERENCES - UI FRAMEWORK -->
	<!-- ============================================================================ -->
	<ItemGroup Label="UI Framework">
		<PackageReference Include="MudBlazor" />
		<PackageReference Include="Extensions.MudBlazor.StaticInput" />
	</ItemGroup>

	<!-- ============================================================================ -->
	<!-- PACKAGE REFERENCES - LOGGING -->
	<!-- ============================================================================ -->
	<ItemGroup Label="Logging">
		<PackageReference Include="Serilog" />
		<PackageReference Include="Serilog.Extensions.Hosting" />
		<PackageReference Include="Serilog.Sinks.Console" />

	</ItemGroup>



	<!-- ============================================================================	-->
	<!-- 	Analyzers																	-->
	<!-- 	MudBlazor includes a Roslyn analyzer to detect common						-->
	<!--	MudBlazor issues at compile time.											-->
	<!-- 	https://mudblazor.com/features/analyzers#mud0002							-->
	<!-- ============================================================================	-->

	<PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
		<MudAllowedAttributePattern>LowerCase</MudAllowedAttributePattern>
	</PropertyGroup>

	<!-- ============================================================================ -->
	<!-- PACKAGE REFERENCES - CORE FRAMEWORK -->
	<!-- ============================================================================ -->
	<ItemGroup Label="Core Framework">
		<PackageReference Include="FluentResults" />
	</ItemGroup>
</Project>