<Project Sdk="Microsoft.NET.Sdk">




	<!-- ============================================================================ -->
  <!-- CORE PROPERTIES -->
  <!-- ============================================================================ -->
  <PropertyGroup>
    <!-- Target Framework -->
    <TargetFramework>net9.0</TargetFramework>
    
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>

    <!-- Language Features -->
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>


  </PropertyGroup>

  <!-- ============================================================================ -->
  <!-- PUBLISHING PROPERTIES -->
  <!-- ============================================================================ -->
  <PropertyGroup>
    <!-- Publishing Enhancements -->
    <EnableDynamicPgo>true</EnableDynamicPgo>
    <TieredCompilation>true</TieredCompilation>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="Helpers\" />
  </ItemGroup>




</Project>
