<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="9.3.1" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>

    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAspireHost>true</IsAspireHost>
    <UserSecretsId>6c5b9e36-80c7-4631-a60f-c6ee9b2ab7b2</UserSecretsId>
  </PropertyGroup>

  <ItemGroup Label="Hosting">
    <PackageReference Include="Aspire.Hosting.AppHost" />
  </ItemGroup>

  <ItemGroup Label="Data Access">

	  <PackageReference Include="Aspire.Hosting.Qdrant" />
      <PackageReference Include="Aspire.Hosting.SqlServer" />
	  <PackageReference Include="Aspire.Microsoft.EntityFrameworkCore.SqlServer" />

  </ItemGroup>



  <ItemGroup>
	  <PackageReference Include="Aspirant.Hosting.Yarp" />
	  <PackageReference Include="Aspire.Hosting" />
	  <PackageReference Include="Aspire.Hosting.PostgreSQL" />
	  <PackageReference Include="Aspire.Hosting.Python" />

	  <PackageReference Include="Aspire.Hosting.Redis" />
	  <PackageReference Include="Aspire.Hosting.NodeJs" />
	  <PackageReference Include="Aspire.Hosting.RabbitMQ" />
	  <PackageReference Include="Aspire.Hosting.MongoDB" />
	  <PackageReference Include="Aspire.Hosting.Seq" />

	  <PackageReference Include="CommunityToolkit.Aspire.EventStore" />
	  <PackageReference Include="CommunityToolkit.Aspire.Hosting.Ollama" />
	  <PackageReference Include="CommunityToolkit.Aspire.Hosting.RavenDB" />
	  <PackageReference Include="CommunityToolkit.Aspire.Hosting.Sqlite" />
	  <PackageReference Include="CommunityToolkit.Aspire.Hosting.SqlServer.Extensions" />
	  <PackageReference Include="CommunityToolkit.Aspire.OllamaSharp" />
	  <PackageReference Include="Dependify.Aspire.Hosting" />
	  <PackageReference Include="Keycloak.AuthServices.Aspire.Hosting" />
	  <PackageReference Include="Microsoft.Extensions.Hosting" />
	  <PackageReference Include="Microsoft.Extensions.ServiceDiscovery" />
	  <PackageReference Include="Nextended.Aspire" />
	  <PackageReference Include="NorthernNerds.Aspire.Hosting.Neo4j" />
	  <PackageReference Include="Raygun.Aspire.Hosting.Ollama" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Presentation\ExxerAI.UI.Dashboard\ExxerAI.Aspire.Dashboard.csproj" />
    <ProjectReference Include="..\..\Presentation\ExxerAI.UI\ExxerAI.UI.csproj" />
  </ItemGroup>

</Project>
