// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Compiler", "CS1591:Missing XML comment for publicly visible type or member", Justification = "<Pending>", Scope = "member", Target = "~M:ExxerAI.Application.Interfaces.AgentOrchestrator.ExecuteAsync(ExxerAI.Domain.ValueObjects.AgentContext,System.Threading.CancellationToken)~System.Threading.Tasks.Task{ExxerAI.Domain.ValueObjects.AgentResult}")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML comment for publicly visible type or member", Justification = "<Pending>", Scope = "member", Target = "~M:ExxerAI.Application.Interfaces.AgentOrchestrator.GetAgentStatusAsync~System.Threading.Tasks.Task{System.String}")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML comment for publicly visible type or member", Justification = "<Pending>", Scope = "member", Target = "~M:ExxerAI.Application.Interfaces.IAgent.ExecuteAsync(ExxerAI.Domain.ValueObjects.AgentContext,System.Threading.CancellationToken)~System.Threading.Tasks.Task{ExxerAI.Domain.ValueObjects.AgentResult}")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML comment for publicly visible type or member", Justification = "<Pending>", Scope = "member", Target = "~M:ExxerAI.Application.Interfaces.IAgent.ExecuteAsync(System.String,System.String)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML comment for publicly visible type or member", Justification = "<Pending>", Scope = "member", Target = "~M:ExxerAI.Application.Interfaces.IAgent.GetAgentStatusAsync~System.Threading.Tasks.Task{System.String}")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML comment for publicly visible type or member", Justification = "<Pending>", Scope = "member", Target = "~M:ExxerAI.Application.Interfaces.IAgentOrchestrator.ExecuteAgentAsync(System.String,System.String)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML comment for publicly visible type or member", Justification = "<Pending>", Scope = "member", Target = "~M:ExxerAI.Application.Interfaces.IAgentOrchestrator.ExecuteAsync(ExxerAI.Domain.ValueObjects.AgentContext,System.Threading.CancellationToken)~System.Threading.Tasks.Task{ExxerAI.Domain.ValueObjects.AgentResult}")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML comment for publicly visible type or member", Justification = "<Pending>", Scope = "member", Target = "~M:ExxerAI.Application.Interfaces.IAgentOrchestrator.GetAgentStatusAsync~System.Threading.Tasks.Task{System.String}")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML comment for publicly visible type or member", Justification = "<Pending>", Scope = "member", Target = "~M:ExxerAI.Application.Interfaces.IAgentService.ExecuteAgentTaskAsync(System.String,System.String)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML comment for publicly visible type or member", Justification = "<Pending>", Scope = "member", Target = "~M:ExxerAI.Application.Interfaces.IAgentService.ExecuteTaskAsync(System.String,System.String)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML comment for publicly visible type or member", Justification = "<Pending>", Scope = "member", Target = "~M:ExxerAI.Application.Services.GeneralPurposeAgent.#ctor(Microsoft.Extensions.Logging.ILogger{ExxerAI.Application.Services.GeneralPurposeAgent},ExxerAI.Application.Interfaces.ILLMProvider,System.String,System.String)")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML comment for publicly visible type or member", Justification = "<Pending>", Scope = "member", Target = "~P:ExxerAI.Application.Services.GeneralPurposeAgent.AgentId")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML comment for publicly visible type or member", Justification = "<Pending>", Scope = "member", Target = "~P:ExxerAI.Application.Services.GeneralPurposeAgent.AgentType")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML comment for publicly visible type or member", Justification = "<Pending>", Scope = "type", Target = "~T:ExxerAI.Application.Interfaces.IAgentOrchestrator")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML comment for publicly visible type or member", Justification = "<Pending>", Scope = "type", Target = "~T:ExxerAI.Application.Interfaces.IAgentService")]
[assembly: SuppressMessage("Compiler", "CS1591:Missing XML comment for publicly visible type or member", Justification = "<Pending>", Scope = "type", Target = "~T:ExxerAI.Application.Services.AppComunication")]
