<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ExxerAI.Application\ExxerAI.Application.csproj" />
    <ProjectReference Include="..\ExxerAI.Domain\ExxerAI.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>


	  <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
	  <RestoreLockedMode>false</RestoreLockedMode>
	  <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
	  <DisablePackageRestore>true</DisablePackageRestore>

  </PropertyGroup>

</Project>
