<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Google.Apis.Auth" />
    <PackageReference Include="Google.Apis.Drive.v3" />
    <PackageReference Include="Google.Apis.Core" />
    <PackageReference Include="UglyToad.PdfPig" />
    <PackageReference Include="FluentResults" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ExxerAI.Application\ExxerAI.Application.csproj" />
    <ProjectReference Include="..\ExxerAI.Domain\ExxerAI.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>




  </PropertyGroup>

</Project>
