<Project Sdk="Microsoft.NET.Sdk.Web">

  <!-- ============================================================================ -->
  <!-- CORE PROPERTIES -->
  <!-- ============================================================================ -->
  <PropertyGroup>
    <!-- Target Framework Defined on Build.Props Do to Add Another here-->
    
	  <TreatWarningsAsErrors>false</TreatWarningsAsErrors>

    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <!-- Language Features -->
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <!-- Documentation -->
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>


  </PropertyGroup>

  <!-- ============================================================================ -->
  <!-- PUBLISHING PROPERTIES -->
  <!-- ============================================================================ -->
  <PropertyGroup>
    <!-- Publishing Enhancements -->
    <EnableDynamicPgo>true</EnableDynamicPgo>
    <TieredCompilation>true</TieredCompilation>
    <PublishSingleFile>false</PublishSingleFile>
    <SelfContained>false</SelfContained>
  </PropertyGroup>

  <!-- ============================================================================ -->
  <!-- PACKAGE REFERENCES - WEB API -->
  <!-- ============================================================================ -->
  <ItemGroup Label="Web API">
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>

  <!-- ============================================================================ -->
  <!-- PROJECT REFERENCES -->
  <!-- ============================================================================ -->
  <ItemGroup Label="Infrastructure References">
    <ProjectReference Include="..\..\Core\ExxerAI.Application\ExxerAI.Application.csproj" />
    <ProjectReference Include="..\..\Core\ExxerAI.Domain\ExxerAI.Domain.csproj" />
    <ProjectReference Include="..\ExxerAI.Infrastructure\ExxerAI.Infrastructure.csproj" />
  </ItemGroup>

</Project>
