<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-ExxerAI.UI-e580dab3-dd33-45be-9ba8-4cf6cf5dc0db</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <None Update="Data\app.db" CopyToOutputDirectory="PreserveNewest" ExcludeFromSingleFile="true" />
  </ItemGroup>


  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore"  />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer"  />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" />
    <PackageReference Include="MudBlazor"  />
    <PackageReference Include="Extensions.MudBlazor.StaticInput"  />

    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI"/> 
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" />

  </ItemGroup>

</Project>