<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>

		<RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
		<RestoreLockedMode>false</RestoreLockedMode>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<DisablePackageRestore>true</DisablePackageRestore>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="coverlet.collector" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="xunit"  />
		<PackageReference Include="xunit.runner.visualstudio"  />
	</ItemGroup>

	<ItemGroup>
		<Using Include="Xunit" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="NSubstitute" />
		<PackageReference Include="Shouldly" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\ExxerAI.Orchestration\ExxerAI.Orchestration.csproj" />
		<ProjectReference Include="..\..\ExxerAI.Domain\ExxerAI.Domain.csproj" />
	</ItemGroup>

</Project>
